# bogus entry since we don't install sudo
# but this file needs to be non-empty
/usr/bin/sudo
## -rwsr-s--x 1 gentoouser gentoouser 99K May 15 12:08 /usr/bin/procmail
#/usr/bin/procmail
## -rwxr-s--x 1 gentoouser gentoouser 22K May 15 12:08 /usr/bin/lockfile
#/usr/bin/lockfile
## -rwxr-sr-x 1 gentoouser gentoouser 15K May 15 12:22 /usr/bin/dotlock
#/usr/bin/dotlock
## -rwsr-xr-x 1 gentoouser gentoouser 46K May 15 12:22 /usr/sbin/mda
#/usr/sbin/mda
## -rwsr-xr-x 1 gentoouser gentoouser 19K May 15 12:29 /usr/bin/libgtop_server2
#/usr/bin/libgtop_server2
## -rws--x--x 1 gentoouser gentoouser 443K May 15 12:45 /usr/lib64/misc/ssh-keysign
#/usr/lib64/misc/ssh-keysign
## -rwsr-xr-x 1 gentoouser gentoouser 35K May 15 13:14 /usr/bin/fusermount
#/usr/bin/fusermount
## -rwsr-xr-x 1 gentoouser gentoouser 452K May 15 13:32 /usr/bin/screen-4.8.0
#/usr/bin/screen-4.8.0
## -rwxr-sr-x 1 gentoouser gentoouser 23K Nov  2 17:18 /usr/bin/dotlockfile
#/usr/bin/dotlockfile
## -rwx--s--x 1 oldeman oldeman 15K Jun 22 19:48 /usr/lib64/misc/utempter/utempter
#/usr/lib64/misc/utempter/utempter
## -rwxr-sr-x 1 oldeman oldeman 91K Jun 22 22:31 /usr/bin/chage
#/usr/bin/chage
## -rwsr-xr-x 1 oldeman oldeman 66K Jun 22 22:31 /usr/bin/chfn
#/usr/bin/chfn
## -rwsr-xr-x 1 oldeman oldeman 61K Jun 22 22:31 /usr/bin/chsh
#/usr/bin/chsh
## -rwxr-sr-x 1 oldeman oldeman 36K Jun 22 22:31 /usr/bin/expiry
#/usr/bin/expiry
## -rwsr-xr-x 1 oldeman oldeman 83K Jun 22 22:31 /usr/bin/gpasswd
#/usr/bin/gpasswd
## -rwsr-xr-x 1 oldeman oldeman 48K Jun 22 22:31 /usr/bin/newgrp
#/usr/bin/newgrp
## -rwsr-xr-x 1 oldeman oldeman 107K Jun 22 22:31 /usr/bin/passwd
#/usr/bin/passwd
## -rwsr-xr-x 1 oldeman oldeman 58K Jun 22 22:31 /usr/bin/newgidmap
#/usr/bin/newgidmap
## -rwsr-xr-x 1 oldeman oldeman 58K Jun 22 22:31 /usr/bin/newuidmap
#/usr/bin/newuidmap
## -rwsr-xr-x 1 oldeman oldeman 455K Jun 23 14:32 /usr/bin/screen-4.9.1
#/usr/bin/screen-4.9.1
## -rwsr-xr-x 1 oldeman oldeman 19K Jun 26 01:22 /usr/libexec/libgtop_server2
#/usr/libexec/libgtop_server2
## -rwxr-s--x 1 oldeman oldeman 14K Jun 26 19:29 /usr/libexec/emacs/30.2/x86_64-pc-linux-gnu/movemail
#/usr/libexec/emacs/30.2/x86_64-pc-linux-gnu/movemail
## -rwsr-xr-x 1 oldeman oldeman 71K Jun 29 13:48 /usr/libexec/mate-screensaver-dialog
#/usr/libexec/mate-screensaver-dialog
