[computecanada]
location = /cvmfs/soft.computecanada.ca/gentoo/2026/x86-64-v3/var/db/repos/computecanada
sync-type = git
sync-uri = https://github.com/ComputeCanada/gentoo-overlay.git
sync-git-clone-extra-opts = --branch 2026 --single-branch
priority = 50
