#!/bin/bash

repository_name="${1}"

[[ ${repository_name} == "computecanada" ]] || exit 0

source $(portageq envvar EPREFIX)/lib/gentoo/functions.sh

CONFIGDIR=$(portageq envvar EPREFIX)/etc/portage
ebegin "Updating config"
if [[ -e ${CONFIGDIR} ]]; then
	git -C "${CONFIGDIR}" pull -q --ff-only
else
	git clone -q https://github.com/ComputeCanada/gentoo-config.git "${CONFIGDIR}"
fi
eend $? "Try to remove ${CONFIGDIR}"

# remove temporary package files from bootstrap
rm -f "${CONFIGDIR}"/make.profile/package.*
